### PR TITLE
use correct array keys to access the statistics

### PR DESCRIPTION
**Pull request by schiessle**
use the correct array keys to show all the available statistics.

### CODE REVIEW

**Comment by schiessle** [comment]
@nickvergessen please have a short look

**Comment by nickvergessen** [comment]
There was 1 failure:

1) OCA\Survey_Server\Controller\PageControllerTest::testIndex

**Comment by nickvergessen** [comment]
Also kill php 5.4 and 5.5: https://github.com/nextcloud/survey_server/blob/master/.travis.yml#L4-L5 
and use 5.6 here https://github.com/nextcloud/survey_server/blob/master/.travis.yml#L41-L44

**Comment by schiessle** [comment]
@nickvergessen fixed :smiley:

**Comment by nickvergessen** [comment]
:+1:

**Pull request merged**
