### PR TITLE
Fix outdated classes

### PR DESCRIPTION
**Pull request by MorrisJobke**
For nextcloud/server#6605

@schiessle Could you then publish a new app for the App Store so that we can update that properly.

### CODE REVIEW

**Comment by nickvergessen** [comment]
This will break our setup 🙊 👎

**Comment by MorrisJobke** [comment]
Why?

**Comment by MorrisJobke** [comment]
@nickvergessen 🏓

**Review by nickvergessen — APPROVED** [review]

**Comment by MorrisJobke** [comment]
Added in https://github.com/nextcloud/server/commit/9b05f37fad88fdf78fdfee9473c27ba5be12abb2#diff-b4aae31b73dc607331c69cc01d9179d8

**Comment by nickvergessen** [comment]
Oo this was added in 9? Oo

**Comment by MorrisJobke** [comment]
> Oo this was added in 9? Oo

yep :D

**Pull request merged**
